INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Gegrilde Kipsandwich', 'Sappige gegrilde kipfilet met sla, tomaat en mayo', 8.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Classic Caesar Salad', 'Krokante romaine sla, croutons en Caesar dressing', 7.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Veggie Wrap', 'Gemengde groenten met hummus in een volkoren wrap', 6.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Beef Burger', 'Huisgemaakte rundvleesburger met cheddar kaas en augurken', 9.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Tonijnsalade', 'Verse tonijn met gemengde sla en balsamico dressing', 8.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Caprese Panini', 'Tomaat, mozzarella en basilicum op geroosterd brood', 7.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Clubsandwich', 'Drie lagen brood met kip, bacon, sla en tomaat', 8.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Quinoasalade', 'Quinoa met gegrilde groenten en feta', 7.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Spinazie en Feta Quiche', 'Quiche met spinazie, feta en een korst van bladerdeeg', 7.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Lunch', 'Avocado Toast', 'Geroosterd brood met avocado, tomaat en een scheutje olijfolie', 6.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Steak Frites', 'Gegrilde steak geserveerd met frietjes', 14.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Spaghetti Carbonara', 'Romige pasta met spek en Parmezaanse kaas', 12.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Geschroeide Zalm', 'Zalmfilet met citroenboter saus en asperges', 15.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Kip Alfredo', 'Gegrilde kip met fettuccine in een romige Alfredo saus', 13.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Ratatouille', 'Traditionele Franse groentestoofpot met kruiden', 11.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Lasagne Bolognese', 'Laagjes pasta met rundergehakt, tomatensaus en bechamel', 13.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Lamskoteletten', 'Gekruide lamskoteletten met munt-yoghurt saus', 17.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Curry met Groenten', 'Romige curry met seizoensgroenten', 11.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Mosselen met Friet', 'Gestoomde mosselen in witte wijnsaus met frietjes', 14.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Diner', 'Gegrilde Aubergine', 'Gegrilde aubergine met tahini en granaatappel', 12.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Cheesecake', 'Rijke en romige cheesecake met een graham cracker bodem', 5.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Chocolademousse', 'Lichte en luchtige chocolademousse', 4.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Appeltaart', 'Traditionele appeltaart met een krokante korst', 4.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Citroentaart', 'Frisse citroentaart met een boterachtige korst', 4.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Brownie', 'Een decadente chocoladebrownie', 3.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Panna Cotta', 'Zachte panna cotta met een vleugje vanille', 4.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Tiramisu', 'Klassieke Italiaanse tiramisu met mascarpone en koffie', 5.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'IJscoupe', 'Drie bollen ijs naar keuze met slagroom', 4.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Crème Brûlée', 'Gebakken custard met een krokant suikerlaagje', 5.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Dessert', 'Chocolade Fondant', 'Warme chocoladecake met een vloeibare kern', 5.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Americano', 'Heet water met een shot espresso', 2.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Latte', 'Geschuimde melk met een shot espresso', 3.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'IJsthee', 'Verfrissende koude thee met citroen', 2.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Sinaasappelsap', 'Vers geperst sinaasappelsap', 3.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Rode Wijn', 'Een glas rode wijn', 5.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Bier', 'Pilsener bier', 4.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Cappuccino', 'Espresso met gestoomde melk en melkschuim', 3.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Minerale Water', 'Spa blauw of rood', 2.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Groene Thee', 'Licht en verfrissende groene thee', 2.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Smoothie', 'Vers fruit smoothie', 4.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Espresso', 'Sterke koffie in een kleine kop', 2.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Frisdrank', 'Keuze uit cola, sinas, of lemon-lime', 2.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Chai Latte', 'Gekruide thee met gestoomde melk', 3.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Milkshake', 'Vanille, chocolade of aardbei milkshake', 4.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Mojito', 'Verfrissende cocktail met munt en limoen', 6.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Whisky', 'Sterke drank van gerst of rogge', 6.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Koude Koffie', 'Verfrissende koude koffie met melk', 3.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Appelsap', 'Vers geperst appel,', 3.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Warme Chocolade', 'Warme chocolademelk met slagroom', 3.50);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Margarita', 'Klasmenumenusieke cocktail met tequila, limoen en triple sec', 7.00);
INSERT INTO menu (category, dish, description, price) VALUES ('Drank', 'Thee', 'Geserveerd in verschillende smaken', 2.00);
